# include_recipe "bootstrap::base"
# include_recipe "bootstrap::encfs"
# include_recipe "bootstrap::hipchat"
# include_recipe "bootstrap::java"
# include_recipe "bootstrap::spotify"
# include_recipe "bootstrap::sublime"
# include_recipe "bootstrap::systray"
# include_recipe "bootstrap::vagrant"
include_recipe "bootstrap::docker"
# include_recipe "bootstrap::zsh"
# include_recipe "bootstrap::steam"
